# Fedora
ansible_host: 192.168.0.7
ansible_user: ansible
ansible_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37626337646433386135383330623238363431626338636435646534643935623430303435383632
  3133356266303232306137323637383363373866623166660a386233643265363030366562663433
  63356634376233386465653262646530356264616365386366393830386331343231383932383866
  6430393032383732630a326336386566643631346461303565373864313161306664616332633937
  32313639663262386134306165306335396430623531666337393333333033386661
