---
- name: localhost test Playbook
  hosts: localhost
  gather_facts: yes

  vars:
    - list1: [test1, test2, test3]
    - list2: [test4, test5, test6]

  tasks:
    - name: hello world
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ list1 }}"
        - "{{ list2 }}"
